import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Tests",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}

export function Box({children}) {
  return (
    <div className="flex gap-3 w-full h-screen p-6 bg-base">
      {children}
    </div>
  )
}
